services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Usar el Dockerfile de producción
    container_name: frontend-prod
    ports:
      - "3000:80" # Producción: expone directamente en el puerto 80
    environment:
      - NODE_ENV=production
    networks:
      - ms-network

  database-dev:
    image: postgres:15
    container_name: pgdatabase-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ipqq7890
      POSTGRES_DB: desarrollo
    ports:
      - "55555:5432"  # <-- un puerto expuesto sólo para dev
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ms-network

volumes:
  pgdata-dev:
    name: microserviciosv1_pgdata_dev