services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/.env.development:/app/.env # ğŸ‘ˆ Monta el archivo directamente
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  database:
    container_name: pgdatabase-dev
    ports:
      - "5432:5432"  # â† En dev, expÃ³n en 5433 si ya usas 5432 localmente
    volumes:
      - ./db/dev-init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata-dev:/var/lib/postgresql/data  # â† Volumen distinto al de producciÃ³n

volumes:
  pgdata-dev: