services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Usar el Dockerfile de producción
    container_name: frontend-prod
    ports:
      - "3000:80" # Producción: expone directamente en el puerto 80
    environment:
      - NODE_ENV=production
    networks:
      - ms-network
