services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/.env.development:/app/.env # ðŸ‘ˆ Monta el archivo directamente
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  auth:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.21.15.23:55555/auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ipqq7890

  turnos:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.21.15.23:55555/turnos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ipqq7890

  commonservices:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.21.15.23:55555/commonservices
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ipqq7890

  formularios:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.21.15.23:55555/formularios
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ipqq7890

